### PR TITLE
Find default branch correctly

### LINKED ISSUE #131: Incorrect default branch detection
The `find_default_branch` function is flawed: getting `.name()` on `head` [will _always_ return `HEAD`](https://docs.rs/gix/latest/gix/struct.Head.html#method.name).

Patch to fix:

```diff
diff --git c/src/database/indexer.rs w/src/database/indexer.rs
index 72cf47b..da50aee 100644
--- c/src/database/indexer.rs
+++ w/src/database/indexer.rs
@@ -97,7 +97,13 @@ fn update_repository_metadata(scan_path: &Path, repository_list: Option<&Path>,
 }
 
 fn find_default_branch(repo: &gix::Repository) -> Result<Option<String>, anyhow::Error> {
-    Ok(Some(repo.head()?.name().as_bstr().to_string()))
+    Ok(Some(
+        repo.head()?
+            .referent_name()
+            .context("Could not find default branch")?
+            .as_bstr()
+            .to_string(),
+    ))
 }
 
 fn find_last_committed_time(repo: &gix::Repository) -> Result<OffsetDateTime, anyhow::Error> {
```

### PR DESCRIPTION
**Pull request by 9p4**
Resolves #131

### CODE REVIEW

File: src/database/indexer.rs [hunk 1]
```diff
@@ -97,7 +97,17 @@ fn update_repository_metadata(scan_path: &Path, repository_list: Option<&Path>,
 }
 
 fn find_default_branch(repo: &gix::Repository) -> Result<Option<String>, anyhow::Error> {
-    Ok(Some(repo.head()?.name().as_bstr().to_string()))
+    if repo.head()?.is_detached() {
+        Ok(None)
```
Comment (w4) [inline src/database/indexer.rs:101]: I think this is redundant because `referent_name` already checks if detached and returns None so could've been written:

```rust
let head = repo.head()?;

let Some(referent) = head.referent_name() else {
    return Ok(None);
};

Ok(Some(referent.as_bstr().to_string()))
```

Not a huge issue though. Thanks for the contribution
